version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - 3000:80
    depends_on:
      - backend
    networks:
      - my-custom-network
  backend:
    build: ./backend
    ports:
      - 5001:5000
    environment:
        DB_HOST: database
        DB_USER: postgres
        DB_NAME: postgres
        DB_PASS: password
    depends_on:
        - database
  database:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my-custom-network
volumes:
  pgdata:
networks:
  my-custom-network:
    driver: bridge